/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'venka' at '9/5/16 2:20 PM' with Gradle 2.14
 *
 * @author venka, @date 9/5/16 2:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
